### ISSUE TITLE
Frank-runner build fails after commit 9476321740d4b4763718d9bd92927109796e54d8

### ISSUE THREAD

**Issue by dinges2** [ibissource/frank-runner#51]
Running the restart.bat to launch Tomcat results in the following error:

![image](https://user-images.githubusercontent.com/55240448/171828212-c6adcd15-2a78-4806-9656-6a56c6825e6b.png)

Changing the latest commits back seems to fix the issue.

**Comment by jacodg** [comment]
The Nexus clean job accidentally cleaned to much last night so the latest Frank!Flow jar was not available anymore. Latest Frank!Flow release is now available on Nexus again. Please retry.

**Comment by dinges2** [comment]
I tried again and the build is successful. My issue is solved, thank you.
