### ISSUE TITLE
Frank2Example5 does not work

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/frank-runner#53]
Frank2Example5 does not work. In the Frank!Console, you see errors that configurations Example1 and Example2 are not found.

The Frank!Runner was started from directory `frank-runner\examples\Frank2Example5` and by accessing the `restart.bat` script in that directory.

![image](https://user-images.githubusercontent.com/6784732/175537117-d068ce92-c163-447d-b528-f01212a9ae04.png)

**Comment by jacodg** [comment]
Some local empty folders needed to be removed
