### ISSUE TITLE
restart.sh fails to run on MacOS with keytool error

### ISSUE THREAD

**Issue by vijairamcharan** [ibissource/frank-runner#57]
As a workaround I had to change the keytool path to `${jdk.dir}/Contents/Home/bin/keytool` in build.xml in the root. After that change everything started running flawlessly.

**Comment by jacodg** [comment]
Commit https://github.com/ibissource/frank-runner/commit/6261e0c03d87be0b7395b7cdd5223ce512b7b70c should fix it When possible could you test it and let me know the result?
