### ISSUE TITLE
Calling env.bat or env.sh should always produce some output

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/frank-runner#63]
I called the script env.bat to let the Frank!Runner do its downloads. When I ran it another time, there was nothing left to download. I would like to see output also in this case, at least something like "Running env.bat" or "Running env.sh".

I would like this for the following reason. I use this script in the GitHub tests of ladybug-frontend. I save the resulting output to a file that I download as artifact. Testers download this file to check the operation of the ladybug tests. Having an empty file is confusing then.

**Comment by jacodg** [comment]
Done: https://github.com/ibissource/frank-runner/commit/8f9a7c085e1717c5f03aec2d053b12c62f9f656f
