### ISSUE TITLE
Problems running on MAC  FR_DIR not resolved properly

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/frank-runner#72]
It looks like on mac the directories are not resolved correctly

FR_DIR="`pwd`/${BASH_SOURCE%/*}/" in start.sh should have resolved to "/User/m~~~~~~r/Projects/frank-runner/" 

it resolves to User/m~~~~~~r/Projects/MyFirstFrank//User/m~~~~~~r/Projects/frank-runner/

![image](https://user-images.githubusercontent.com/3921911/220042147-55c4f293-9d1d-42bc-ba12-83efaea7e7f1.png)

**Comment by jjansenvr** [comment]
@jacodg maybe something for Martijn to look in to, No hurry we will fix it manually for now

**Comment by jjansenvr** [comment]
removing the pwd in FR_DIR="pwd/${BASH_SOURCE%/*}/ in all script solved the first problem

a second problem is having an restart.sh in the 
[restart.zip](https://github.com/ibissource/frank-runner/files/10861161/restart.zip)

**Comment by jacodg** [comment]
A restart.sh in the restart.zip?

**Comment by jacodg** [comment]
For the restart.sh in the project: The path in the documentation was wrong, this is fixed now: https://github.com/ibissource/frank-runner/commit/0be29295effc2acca0225555d058fc990ae212ac

**Comment by jacodg** [comment]
Should be fixed now: https://github.com/ibissource/frank-runner/blob/8a92e7469e38f7e52391d2a482157447935d21d0/build.xml#L957
