### ISSUE TITLE
Frank runner not working

### ISSUE THREAD

**Issue by ashishtank** [ibissource/frank-runner#74]
Hi Guys,

Frank runner was working fine after running start.bat file but after restart of laptop it stopped working with below error.

**_IBIS Startup Failed
For some reason, the IBIS application failed to start up.

Please examine the startup-log and try restarting the server._**

NOTE: The IBIS application will automatically retry to startup every minute.
<img width="958" alt="image" src="https://user-images.githubusercontent.com/7521477/230918784-3f183934-494b-4919-b191-893a82ce031d.png">

Any help is highly appreciated. Do we have plug and play docker images that can be used without much configuration?

PS: Frank flow just works fine.

Regards,
Ashish

**Comment by nitinghaghada** [comment]
Hello Frank Team,

I am also facing same issue while trying to run frank framework on my local machine.

Regards,
Nitin

**Comment by ashishtank** [comment]
Hi Frank Team,

Tried frank runner on mac os and facing same issue over there as well. Could you please help with it?
From browser console log it looks like /iaf/api/* endpoint is not working.

Regards,
Ashish

**Comment by jacodg** [comment]
Hi guys,

It seems to be a problem with the latest F!F version. The Frank!Runner by default always checks for and downloads the latest version. You can create a frank-runner.properties with an older 7.9 version (like 7.9-20230330.214747) (find all version on https://nexus.frankframework.org/service/rest/repository/browse/public/org/ibissource/ibis-adapterframework-webapp/) or use the latest stable version ff.version=7.8

For more information see:

https://github.com/ibissource/frank-runner#frankframework-version

Regards, Jaco

**Comment by ashishtank** [comment]
Hi Jaco

Thanks for quick response. Let me try setting the version.

Regards,
Ashish

**Comment by ashishtank** [comment]
Closing as main issue is solved.
